language: php

php:
  - '7.1'

services:
  - docker

before_install:
  - cp db.env.example db.env
  - cp api/.env.example api/.env
  - cp api/db.env.example api/db.env
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker-compose up -d --build
  - "curl -X POST \
    http://localhost/api/v1/login \
    -H 'cache-control: no-cache' \
    -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
    -F 'username=adam' \
    -F 'password=pass4dev'"
  - cd api/
  - composer install --no-interaction
  - "curl -X POST \
    http://localhost/api/v1/login \
    -H 'cache-control: no-cache' \
    -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
    -F 'username=adam' \
    -F 'password=pass4dev'"
  - docker pull postman/newman


script:
  - docker run -v "$(pwd)/docker/newman/collections":/etc/newman -t  postman/newman run -e jmp.postman_environment.json -n 2  jmp.postman_collection.json
