language: node_js

node_js:
  - "node"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

services:
  - docker

before_install:
  - cp db.env.example db.env
  - cp api/.env.example api/.env
  - cp api/db.env.example api/db.env
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker-compose up -d --build
  - "curl -X POST \
    http://localhost/api/v1/login \
    -H 'cache-control: no-cache' \
    -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
    -F 'username=adam' \
    -F 'password=pass4dev'"
  - cd api/
  - composer install --no-interaction
  - "curl -X POST \
    http://localhost/api/v1/login \
    -H 'cache-control: no-cache' \
    -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
    -F 'username=adam' \
    -F 'password=pass4dev'"


script:
  - node_modules/.bin/newman run docker/newman/collections/jmp.postman_collection.json -e docker/newman/collections/jmp.postman_environment.json -n 2