language: php

php:
  - '7.1'

services:
  - docker

before_install:
  # Set environment variables
  - make cp-env
  # Stop all databases possibly blocking the 3306 port
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

script:
  - make build-up-prod
  - make wait-for-db
  - make test-local dir="$(pwd)"
  - make down-prod
  - make build-up-dev
  - make wait-for-db
  - make test-local dir="$(pwd)"
