language: php

php:
  - '7.1'

services:
  - docker

before_install:
  # Set environment variables
  - make cp-env
  # Stop all databases possibly blocking the 3306 port
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

install:
  # Build and start the containers
  - make build-up
  - make wait-for-db

script:
  - make test dir="$(pwd)"
