version: '3.7'

volumes:
  dbdata:
    driver: local

services:

  # PHP
  app:
    build:
      context: api
      dockerfile: Dockerfile.prod
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: app
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    env_file:
      - api/db.env
      - api/.env

  # Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d.prod/:/etc/nginx/conf.d/
      - ./vue/dist/:/var/www/public

  frontend:
    build:
      context: vue
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - API=http://localhost/api
    container_name: frontend

  # MariaDB
  db:
    image: mariadb:10.4
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - api/db.env
      - db.env
    healthcheck:
      test: mysql --protocol=TCP -hlocalhost -u$$DB_USERNAME -p$$DB_PASSWORD -e 'SELECT 1'
      interval: 1s
      timeout: 1s
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/db/:/docker-entrypoint-initdb.d/
