version: '3'

volumes:
  dbdata:
    driver: local

services:

  # PHP
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./api/:/var/www

  # Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/log/nginx/:/var/log/nginx/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./vue/dist/:/var/www/public

  # MariaDB
  db:
    image: mariadb:10.3
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    env_file:
      - api/db.env
      - db.env
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/db/:/docker-entrypoint-initdb.d/
