version: '3'

services:
  npm:
    image: node:8-alpine
    working_dir: /vue
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - ./docker/scripts/vue-build.sh:/scripts/vue-build.sh
      - ./vue/:/vue/
    command: /scripts/vue-build.sh
